# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15382f4d4965bd0d3329b32a1a2e33df014aeb8ff87d4ec78edc8847d14b035663a0a363205b1458f25e2ea97b44e0a710a691adec3d92d9b66e217a7ddcceb5

test:
  secret_key_base: 3cd66a1114769bc795fb47a15330e680c4a0044bfc9bcde3ac9cdf2b477577aa798028d59616fa87b4f9242f346e2e574e359719dfa9fe7c16133a1fbcefcc66

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
